# Generated by Django 5.2.7 on 2025-10-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='imagePath')),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('is_activate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], default='student', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounts.myuser')),
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('cv', models.FileField(upload_to='instructor/cv/')),
                ('speciality', models.CharField(max_length=50)),
                ('heighest_degree', models.CharField(max_length=100)),
                ('number_of_published_courses', models.IntegerField(default=0)),
                ('student_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('experience_years', models.IntegerField(default=0)),
            ],
            bases=('accounts.myuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.myuser')),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True)),
                ('total_credits', models.IntegerField(default=0)),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('badges', models.TextField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
            ],
            bases=('accounts.myuser',),
        ),
    ]
