# Generated by Django 5.2.7 on 2025-10-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='accounts.role'),
        ),
    ]
