# Generated by Django 5.2.7 on 2025-10-22 09:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_video_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('details', models.TextField(blank=True, null=True)),
                ('course_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='module.module')),
            ],
        ),
    ]
