# Generated by Django 5.2.7 on 2025-10-25 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_video_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('details', models.TextField(blank=True, null=True)),
                ('course_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='module.module')),
            ],
        ),
        migrations.CreateModel(
            name='LessonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='lesson.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='accounts.student')),
            ],
        ),
    ]
