# Generated by Django 5.2.7 on 2025-10-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='title',
        ),
    ]
