# Generated by Django 5.2.7 on 2025-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='trainee/images/')),
                ('language', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_hours', models.IntegerField()),
                ('content', models.TextField()),
                ('reviews', models.TextField()),
                ('enroll_numbers', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
