# Generated by Django 5.2.7 on 2025-10-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Course_id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='isactive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='updateddate',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='course',
            name='in_progress_limited',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.instructors'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enroll_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
