# Generated by Django 5.2.7 on 2025-10-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_content_remove_course_reviews_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
