# Generated by Django 5.2.7 on 2025-10-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_student_total_credits_and_more'),
        ('categories', '0002_delete_categorycourse'),
        ('courses', '0003_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.instructors'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='course_cateory', to='categories.category'),
        ),
    ]
