# Generated by Django 5.2.7 on 2025-10-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_student_total_credits_and_more'),
        ('courses', '0004_remove_course_category_alter_course_instructor_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='enrollment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='courses.studentenrollment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cstransactions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.student'),
        ),
    ]
